name: Enforce Branch Name Convention

on:
  push:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name follows the convention
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"

          regex='^(feature|refactor|test|fix|chore)\/[a-zA-Z0-9\-]+$'

          if [[ ! "$branch_name" =~ $regex ]]; then
            echo "Branch name '$branch_name' does not match the required pattern!" && exit 1
          fi
