name: Enforce Branch Name Convention

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name follows the convention
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          regex='^(feature|refactor|test|fix|chore)\/[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*$'
          if [[ ! "$branch_name" =~ $regex ]]; then
            echo "Branch name '$branch_name' does not match the required pattern!"
            echo "Expected pattern: 'type/description' where type is one of [feature, refactor, test, fix, chore]."
            echo "Description can only contain alphanumeric characters and single hyphens."
            exit 1
          fi
