name: Lint Code Base

permissions:
  statuses: write
  contents: write
  pull-requests: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          FIX_TYPESCRIPT_PRETTIER: true
          FIX_TYPESCRIPT_ES: true
          FIX_JAVACRIPT_ES: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_TSX: true
          FIX_JSX: true
